djfront/djbasic/urls.py
from django.urls import include, path
from djfront.djbasic import views as c


app_name = 'djbasic'


customer_patterns = [
    path('', c.customer_list, name='customer_list'),
    path('add/', c.customer_add, name='customer_add'),
    path('save/', c.customer_save, name='customer_save'),
    path('<int:pk>/edit/', c.customer_edit, name='customer_edit'),
    path('<int:pk>/delete/', c.customer_delete, name='customer_delete'),
    path('datatable/', c.customer_list_datatable,
         name='customer_list_datatable'),
    path('json/', c.customer_json, name='customer_json'),
]

person_patterns = [
    path('', c.person_list, name='person_list'),
    path('add/', c.person_create, name='person_add'),
]

urlpatterns = [
    path('', c.home, name='home'),
    path('customer/', include(customer_patterns)),
    path('person/', include(person_patterns)),
]

djfront/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('', include('djfront.djbasic.urls')),
    path('admin/', admin.site.urls),
]

djfront/core/models.py
from django.db import models

# Create your models here.

djfront/djbasic/models.py
from django.db import models


class Customer(models.Model):
    name = models.CharField('nome', max_length=50)
    email = models.EmailField()

    class Meta:
        ordering = ['name']
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField('nome', max_length=50)
    age = models.IntegerField('idade', null=True, blank=True)
    description = models.TextField('descrição', blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'

    def __str__(self):
        return self.name

djfront/djbasic/forms.py
from django import forms
from .models import Customer, Person


class CustomerForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = ['name', 'email']


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ['name', 'age', 'description']

djfront/core/views.py
from django.shortcuts import render

# Create your views here.

djfront/djbasic/views.py
from django.core import serializers
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.http import (
    HttpResponse, HttpResponseRedirect, HttpResponseNotAllowed, JsonResponse
)
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView
from .models import Customer, Person
from .forms import CustomerForm, PersonForm


def home(request):
    return render(request, 'index.html')


def customer_list(request):
    customers = Customer.objects.all()
    form = CustomerForm()
    ctx = {'customers': customers, 'form': form}
    return render(request, 'djbasic/customer_list.html', ctx)


def customer_list_datatable(request):
    customers = Customer.objects.all()
    form = CustomerForm()
    ctx = {'customers': customers, 'form': form}
    return render(request, 'djbasic/customer_list_datatable.html', ctx)


def customer_json(request):
    customers = Customer.objects.all()
    data = serializers.serialize('json', customers)
    return HttpResponse(data, content_type='application/json')


def customer_add(request):
    return render(request, 'djbasic/customer_add.html')


@csrf_exempt
def customer_save(request):

    # abort if request is not made via POST
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    # abort if request is not made via ajax
    if not request.is_ajax():
        error = {'error': 'This resource requires ajax requests.'}
        return JsonResponse(error, status=422)

    # abort if posted data is not valid
    form = CustomerForm(request.POST)
    if not form.is_valid():
        error = {'error': form.errors}
        return JsonResponse(error, status=422)

    name = form.cleaned_data.get('name')
    email = form.cleaned_data.get('email')
    Customer.objects.create(name=name, email=email)
    message = '{name} ({email}) added.'.format(name=name, email=email)
    return JsonResponse({'message': message})


def customer_edit(request, pk):
    if request.is_ajax() and request.method == 'POST':
        pk = request.POST.get('customer_id')
        # Edita o próprio customer que foi pego pelo id.
        customer = get_object_or_404(Customer, pk=pk)
        # Usando instance não precisa pegar os campos um a um.
        form = CustomerForm(request.POST, instance=customer)

        if not form.is_valid():
            error = {'error': form.errors}
            return JsonResponse(error, status=422)

        # customer.name = request.POST.get('name')
        # customer.email = request.POST.get('email')
        customer.save()
        response = {'status': 'update'}
        return JsonResponse(response)
    else:
        return HttpResponseRedirect(reverse_lazy('customer_list'))


def customer_delete(request, pk):
    if request.is_ajax() and request.method == 'POST':
        pk = request.POST.get('customer_id')
        customer = get_object_or_404(Customer, pk=pk)
        customer.delete()
        response = {'status': 'delete'}
        return JsonResponse(response)
    else:
        return HttpResponseRedirect(reverse_lazy('customer_list'))


person_create = CreateView.as_view(
    model=Person,
    form_class=PersonForm,
    success_url='/person/'
)

person_list = ListView.as_view(model=Person)

djfront/djbasic/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">

    {% block title %}
      <title>Front End Django Test</title>
    {% endblock title %}

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- dataTables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">
    <!-- Semantic -->
    <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
    <!-- main -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

  </head>
  <body>

    {% include "menu.html" %}

    {% block content %}
      
    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'js/semantic.min.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block jssetup %}
      <script src="{% static 'js/django-ajax-setup.js' %}"></script>
    {% endblock jssetup %}

    {% block js %}{% endblock js %}

  </body>
</html>

djfront/djbasic/templates/djbasic/customer_add.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
  
  <form id="meuform" class="form-horizontal col-sm-4 col-lg-4" method="POST">
    <legend>Cadastrar</legend>
    <!-- if this form is sent only via ajax you don't need this:
    {% csrf_token %}
    -->

    <div class="form-group">
      <label for="id_name">Nome</label>
      <input type="text" id="id_name" name="name" class="form-control" value="Regis">
    </div>
    
    <div class="form-group">
      <label for="id_email">e-mail</label>
      <input type="text" id="id_email" name="email" class="form-control" value="regis@example.com">
    </div>

    <div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
      <button type="submit" id="id_submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </form>

{% endblock content %}

{% block js %}
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
{% endblock js %}

djfront/djbasic/templates/djbasic/customer_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}

<div class="container">

  <div class="page-header">
    <button id="btn-customer-add" class="btn btn-primary pull-right" data-toggle="modal" data-target="#modal-customer">
      <!-- O data-target abre o modal com Bootstrap -->
      <span class="glyphicon glyphicon-plus"></span> Adicionar
    </button>

    <h1>Lista de Clientes</h1>
  </div>

  {% if customers %}
    <table id="customers" class="table table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>e-mail</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for customer in customers %}
        <tr class="tr-customer">
          <td>{{ customer.name }}</td>
          <td>{{ customer.email }}</td>
          <td>
            <!-- Delete Customer -->
            <i  class="fa fa-close pull-right js-customer-delete"
                style="color: #0066FF; text-decoration: none; cursor: pointer; margin-left:10px"
                data-id="{{ customer.pk }}"
                data-url="{% url 'djbasic:customer_delete' customer.pk %}"
                ></i>
            <!-- Edit Customer -->
            <i  class="fa fa-edit pull-right js-customer-edit"
                style="color: #0066FF; text-decoration: none; cursor: pointer"
                data-id="{{ customer.pk }}"
                data-url="{% url 'djbasic:customer_edit' customer.pk %}"
                ></i>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}
</div>

<!-- Modal Customer -->
<div id="modal-customer" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <button class="close" aria-label="Close" data-dismiss="modal" type="button">
            <span aria-hidden="True">&times;</span>
          </button>
          <h3 class="modal-title">Cadastrar Cliente</h3>
        </div> <!-- header -->

        <form id="customer-form" action="{% url 'djbasic:customer_save' %}" data-urlredirect="{% url 'djbasic:customer_list' %}" method="POST">
          <div class="modal-body">
            <!-- if this form is sent only via ajax you don't need this:
            { csrf_token %}
            -->
            {{ form|bootstrap }}
          </div> <!-- body -->

          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div> <!-- footer -->
      </form>
    </div>
  </div>
</div>

<!-- Modal Editar Customer -->
<div id="modal-customer-edit" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <button class="close" aria-label="Close" data-dismiss="modal" type="button">
            <span aria-hidden="True">&times;</span>
          </button>
          <h3 class="modal-title">Editar Cliente</h3>
        </div> <!-- header -->

        <form id="customer-form-edit" action="." data-id="" data-url="" data-urlredirect="{% url 'djbasic:customer_list' %}" method="POST">
          <div class="modal-body">
            <!-- if this form is sent only via ajax you don't need this: -->
            {% csrf_token %}
            {{ form|bootstrap }}
          </div> <!-- body -->

          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div> <!-- footer -->
      </form>
    </div>
  </div>
</div>

<!-- Modal Confirm Delete -->
<div id="modal-customer-delete" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Confirmar</h4>
      </div>
        <form id="customer-form-delete" action="." data-id="" data-url="" method="POST">
          <div class="modal-body">
              {% csrf_token %}
              Você quer deletar "<span></span>"?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <input type="submit" class="btn btn-danger" value="Deletar" />
          </div>
        </form>
    </div>
  </div>
</div>


{% endblock content %}

{% block js %}
  <script src="{% static 'js/customer.js' %}"></script>
{% endblock js %}

djfront/djbasic/templates/djbasic/customer_list_datatable.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}

<div class="container">

  <div class="page-header">
    <button id="btn-customer-add" class="btn btn-primary pull-right" data-toggle="modal" data-target="#modal-customer">
      <!-- O data-target abre o modal com Bootstrap -->
      <span class="glyphicon glyphicon-plus"></span> Adicionar
    </button>

    <h1>Lista de Clientes</h1>
  </div>

  {% if customers %}
    <table id="customers" class="table table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>e-mail</th>
          <th></th>
        </tr>
      </thead>
    </table>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

<!-- Modal Customer -->
<div id="modal-customer" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <button class="close" aria-label="Close" data-dismiss="modal" type="button">
            <span aria-hidden="True">&times;</span>
          </button>
          <h3 class="modal-title">Cadastrar Cliente</h3>
        </div> <!-- header -->

        <form id="customer-form" action="{% url 'djbasic:customer_save' %}" data-urlredirect="{% url 'djbasic:customer_list_datatable' %}" method="POST">
          <div class="modal-body">
            <!-- if this form is sent only via ajax you don't need this:
            { csrf_token %}
            -->
            {{ form|bootstrap }}
          </div> <!-- body -->

          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div> <!-- footer -->
      </form>
    </div>
  </div>
</div>

<!-- Modal Editar Customer -->
<div id="modal-customer-edit" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <button class="close" aria-label="Close" data-dismiss="modal" type="button">
            <span aria-hidden="True">&times;</span>
          </button>
          <h3 class="modal-title">Editar Cliente</h3>
        </div> <!-- header -->

        <form id="customer-form-edit" action="." data-id="" data-url="" data-urlredirect="{% url 'djbasic:customer_list_datatable' %}" method="POST">
          <div class="modal-body">
            <!-- if this form is sent only via ajax you don't need this: -->
            {% csrf_token %}
            {{ form|bootstrap }}
          </div> <!-- body -->

          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div> <!-- footer -->
      </form>
    </div>
  </div>
</div>

<!-- Modal Confirm Delete -->
<div id="modal-customer-delete" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Confirmar</h4>
      </div>
        <form id="customer-form-delete" action="." data-id="" data-url="" method="POST">
          <div class="modal-body">
              {% csrf_token %}
              Você quer deletar "<span></span>"?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <input type="submit" class="btn btn-danger" value="Deletar" />
          </div>
        </form>
    </div>
  </div>
</div>


</div> <!-- end container -->

{% endblock content %}

{% block js %}
  <script src="{% static 'js/customer.js' %}"></script>
  <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
  <script>
    $(function () {
      $('#customers').dataTable({
        "processing": true,
        "ajax": {
          "processing": true,
          "url": "{% url 'djbasic:customer_json' %}",
          "dataSrc": ""
        },
        "columns": [
          { "data": "fields.name" },
          { "data": "fields.email" },
          {
            data: null,
            className: "center",
            render: function(data, type, full, meta) {
              return  '<i  class="fa fa-close pull-right js-customer-delete"' + 
                      'style="color: #0066FF; text-decoration: none; ' + 
                      'cursor: pointer; margin-left:10px"data-id="' + data.pk + 
                      '"data-url="' + '/customer/' + data.pk + '/delete/' + '"></i>' + 
                      '<i  class="fa fa-edit pull-right js-customer-edit"' + 
                      'style="color: #0066FF; text-decoration: none; ' + 
                      'cursor: pointer"data-id="' + data.pk + 
                      '"data-url="' + '/customer/' + data.pk + '/edit/' + '"></i>'
            }
          },
        ],
        createdRow: function (row, data, index) {
          $(row).addClass('tr-customer');
        }
      });
    });
  </script>
{% endblock js %}

djfront/djbasic/templates/djbasic/includes/customer_form.html
<form action=""></form>

djfront/djbasic/templates/djbasic/person_form.html
{% extends "base.html" %}

{% load semanticui %}

{% block content %}
    <form class="ui form" method="POST">
      <legend>Person Form</legend>
      {% csrf_token %}
      <div class="two fields">
        {{ form.name|semanticui }}
        {{ form.age|semanticui }}
      </div>
      <div>
        <div class="field">
          <label>Description</label>
          <textarea name="description" id="id_description"></textarea>
        </div>
      </div>
      <button class="ui primary button" type="submit" id="id_submit">Submit</button>
    </form>

{% endblock content %}

djfront/djbasic/templates/djbasic/person_list.html
{% extends "base.html" %}

{% block content %}

<div class="container">

	<div class="page-header">
			<a class="ui primary button pull-right" href="{% url 'djbasic:person_add' %}"><i class="fa fa-plus"></i> Adicionar</a>
      <button id="modal-semantic" class="ui button pull-right">Add</button>
		<h1>Lista de Contatos</h1>
	</div>

	{% if object_list %}
		<table class="ui celled table">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Idade</th>
					<th>Descrição</th>
				</tr>
			</thead>
			<tbody>
			{% for person in object_list %}
				<tr>
					<td>{{ person.name }}</td>
					<td>{{ person.age|default:"-" }}</td>
					<td>{{ person.description }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	{% else %}
		<p class="alert alert-warning">Sem itens na lista.</p>
	{% endif %}
</div>

<div class="ui modal">
  <i class="fa fa-close"></i>
  <div class="header">
    Modal Title
  </div>
  <div class="image content">
    <div class="image">
      An image can appear on left or an icon
    </div>
    <div class="description">
      A description can appear on the right
    </div>
  </div>
  <div class="actions">
    <div class="ui button">Cancel</div>
    <div class="ui button">OK</div>
  </div>
</div>

{% endblock content %}

{% block js %}
  <script>
  $("#modal-semantic").on('click', function() {
    $('.ui.modal').modal();
  });
  </script>
{% endblock js %}

djfront/djbasic/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Frontend Django Test">
    <meta name="author" content="Regis Santos">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">

    <title>Frontend Django Test</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Custom CSS -->
    <link href="{% static 'css/landing-page.css' %}" rel="stylesheet">

    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">Frontend Django Test</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'djbasic:customer_list' %}">Basic</a>
                    </li>
                    <!-- <li>
                        <a href="#services">Services</a>
                    </li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li> -->
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'admin:index' %}">Admin</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Frontend Django Test</h1>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="https://github.com/rg3915/frontend" target="_blank" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <li>
                                <a href="https://twitter.com/rg3915" target="_blank" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <!-- <li>
                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                            </li> -->
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Footer -->
    <!-- <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer> -->

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>

</html>

djfront/djbasic/templates/menu.html
<!-- Menu -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'djbasic:home' %}">Home</a></li>
        <li><a href="{% url 'djbasic:customer_list' %}">Clientes</a></li>
        <li><a href="{% url 'djbasic:customer_list_datatable' %}">Clientes DataTable</a></li>
        <!-- <li><a href="{ url 'djbasic:person_list' %}">Contatos</a></li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </div>
  </div>
</div>